# -*- coding: utf-8 -*-
"""DisneyLand.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XifFX0SKtw97rofFp6tALiefy1xKD1ic

# Instalar y cargar librerias
"""

!pip install -U sentence-transformers

import pandas as pd
from sentence_transformers import SentenceTransformer, util

"""# Cargar dataset del realtor"""

df_disney = pd.read_csv('/content/DisneylandReviews.csv', encoding='latin-1')

df_disney.head(10)

"""# Declarar el modelo sentence-transformer"""

model = SentenceTransformer('sentence-transformers/all-MiniLM-L12-v2')

"""# Pasa todos los script del dialogo del csv a espacios vectoriales

"""

embeddings = model.encode(df_disney['Review_Text'], batch_size=64, show_progress_bar=True)

"""# Guardar los vectores con nueva columna llamada embeddings"""

df_disney['embeddings'] = embeddings.tolist()

df_disney

"""# Busqueda semantica vectorial

Ya se puede realuzar la busqueda semantica
"""

query_embedding = model.encode(['Where is the Duck Donal?'])

df_disney['similarity'] = df_disney.embeddings.apply(lambda x : util.cos_sim(x, query_embedding[0] ))

df_disney.sort_values('similarity', ascending=False).head(10)